// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// GameUserDao is the data access object for table game_user.
type GameUserDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns GameUserColumns // columns contains all the column names of Table for convenient usage.
}

// GameUserColumns defines and stores column names for table game_user.
type GameUserColumns struct {
	Id          string // 主键
	Account     string // 账号
	Password    string // 密码
	NickName    string // 昵称
	AvatarImage string // 头像
	Ctime       string // 创建时间
	Uptime      string // 更新时间
}

// gameUserColumns holds the columns for table game_user.
var gameUserColumns = GameUserColumns{
	Id:          "id",
	Account:     "account",
	Password:    "password",
	NickName:    "nick_name",
	AvatarImage: "avatar_image",
	Ctime:       "ctime",
	Uptime:      "uptime",
}

// NewGameUserDao creates and returns a new DAO object for table data access.
func NewGameUserDao() *GameUserDao {
	return &GameUserDao{
		group:   "default",
		table:   "game_user",
		columns: gameUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *GameUserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *GameUserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *GameUserDao) Columns() GameUserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *GameUserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *GameUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *GameUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
