// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// GameUser is the golang structure of table game_user for DAO operations like Where/Data.
type GameUser struct {
	g.Meta      `orm:"table:game_user, do:true"`
	Id          interface{} // 主键
	Account     interface{} // 账号
	Password    interface{} // 密码
	NickName    interface{} // 昵称
	AvatarImage interface{} // 头像
	Ctime       interface{} // 创建时间
	Uptime      interface{} // 更新时间
}
