// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sqlmodel

const TableNameHouseCommon = "house_common"

// HouseCommon mapped from table <house_common>
type HouseCommon struct {
	ID         int32 `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:唯一ID" json:"id"` // 唯一ID
	UserID     int32 `gorm:"column:user_id;type:int;not null;comment:用户ID" json:"user_id"`            // 用户ID
	Level      int32 `gorm:"column:level;type:int;not null;comment:等级" json:"level"`                  // 等级
	GoldCoin   int32 `gorm:"column:gold_coin;type:int;not null;comment:金币" json:"gold_coin"`          // 金币
	Diamond    int32 `gorm:"column:diamond;type:int;not null;comment:钻石" json:"diamond"`              // 钻石
	Strength   int32 `gorm:"column:strength;type:int;not null;comment:体力" json:"strength"`            // 体力
	Experience int32 `gorm:"column:experience;type:int;not null;comment:经验" json:"experience"`        // 经验
}

// TableName HouseCommon's table name
func (*HouseCommon) TableName() string {
	return TableNameHouseCommon
}
