// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// GameUser is the golang structure for table game_user.
type GameUser struct {
	Id          int    `json:"id"          ` // 主键
	Account     string `json:"account"     ` // 账号
	Password    string `json:"password"    ` // 密码
	NickName    string `json:"nickName"    ` // 昵称
	AvatarImage string `json:"avatarImage" ` // 头像
	Ctime       int    `json:"ctime"       ` // 创建时间
	Uptime      int    `json:"uptime"      ` // 更新时间
}
