// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/451008604/socketServerFrame/database/sql/dao/internal"
)

// internalGameUserDao is internal type for wrapping internal DAO implements.
type internalGameUserDao = *internal.GameUserDao

// gameUserDao is the data access object for table game_user.
// You can define custom methods on it to extend its functionality as you wish.
type gameUserDao struct {
	internalGameUserDao
}

var (
	// GameUser is globally public accessible object for table game_user operations.
	GameUser = gameUserDao{
		internal.NewGameUserDao(),
	}
)

// Fill with you ideas below.
