// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package sql

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		HouseAccount: newHouseAccount(db, opts...),
		HouseCommon:  newHouseCommon(db, opts...),
		HouseUser:    newHouseUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	HouseAccount houseAccount
	HouseCommon  houseCommon
	HouseUser    houseUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		HouseAccount: q.HouseAccount.clone(db),
		HouseCommon:  q.HouseCommon.clone(db),
		HouseUser:    q.HouseUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		HouseAccount: q.HouseAccount.replaceDB(db),
		HouseCommon:  q.HouseCommon.replaceDB(db),
		HouseUser:    q.HouseUser.replaceDB(db),
	}
}

type queryCtx struct {
	HouseAccount *houseAccountDo
	HouseCommon  *houseCommonDo
	HouseUser    *houseUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		HouseAccount: q.HouseAccount.WithContext(ctx),
		HouseCommon:  q.HouseCommon.WithContext(ctx),
		HouseUser:    q.HouseUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
